eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9090/eureka/
  instance:
    hostname: localhost
microservice:
  price-service:
    endpoints:
      endpoint:
        uri: http://price-service/asset/prices
  position-service:
    endpoints:
      endpoint:
        uri: http://position-service/positions/getPosition
  eligibility-service:
    endpoints:
      endpoint:
        uri: http://eligibility-service/eligibility/api/v1.0/eligibility
